[package]
name = "python_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "python_wrapper"
crate-type = ["cdylib"]

[dependencies]
wspr_cdk = { path = "../"}
pyo3 = "0.20.0"
